/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package concerttickets;

import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.ImageIcon;
import model.ConcertTicket;

/**
 *
 * @author n.m.borisova
 */
public class TicketDetails extends javax.swing.JPanel {

    /**
     * Creates new form TicketDetails
     */
    public TicketDetails(ConcertTicket ticket) {
        initComponents();
        Path resourceDirectory = Paths.get("src","resources");
        String absolutePath = resourceDirectory.toFile().getAbsolutePath();
        jLblConcertTitle.setText(ticket.getConcertTitle());
        jLblConcertPrice.setText(String.valueOf(ticket.getRegularPrice()));
        jLblConcertPhoto.setIcon(new ImageIcon(absolutePath+"/"+ticket.getPhotoName()));
        jLblConcertLocation.setText(ticket.getLocation());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblConcertPhoto = new javax.swing.JLabel();
        jLblConcertTitle = new javax.swing.JLabel();
        jLblConcertPrice = new javax.swing.JLabel();
        jLblConcertLocation = new javax.swing.JLabel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLblConcertPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblConcertTitle)
                    .addComponent(jLblConcertPrice)
                    .addComponent(jLblConcertLocation))
                .addContainerGap(442, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblConcertTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLblConcertPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLblConcertLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLblConcertPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLblConcertLocation;
    private javax.swing.JLabel jLblConcertPhoto;
    private javax.swing.JLabel jLblConcertPrice;
    private javax.swing.JLabel jLblConcertTitle;
    // End of variables declaration//GEN-END:variables
}
